charts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^index_chart$', views.index_chart, name='index_chart'),
    url(r'^chart_tabel8$', views.chart_tabel8, name='chart_tabel8'),
    url(r'^chart_tabel9$', views.chart_tabel9, name='chart_tabel9'),
    url(r'^chart_tabel10$', views.chart_tabel10, name='chart_tabel10'),
    # fetch data
    url(r'^dl_fetch_chart_data$', views.dl_fetch_chart_data, name='dl_fetch_chart_data'),
    # education
    url(r'^education_summary$', views.education_summary, name='education_summary'),

]

dala/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from tastypie.api import Api
from .import views
# from api.resources import DistrictResource, ProvinceResource, BmfPubMfResource

# v1_api = Api(api_name='v1')
# v1_api.register(DistrictResource())
# v1_api.register(ProvinceResource())
# v1_api.register(BmfPubMfResource())

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    # url(r'^api/', include(v1_api.urls)),
    url(r'^health/', include('health.urls', namespace='health')),
    url(r'^education/', include('education.urls', namespace='education')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^new_charts/', include('new_charts.urls', namespace='new_charts')),
    url(r'^send_email', views.send_email, name='send_email'),

    # report builder
   # url(r'^report_builder/', include('report_builder.urls')),

    # common functions
    url(r'^bs_get_data$', views.bs_get_data, name='bs_get_data'),
    url(r'^bs_get_data_mock$', views.bs_get_data_mock, name='bs_get_data_mock'),
    url(r'^bs_fetch_edit_data$', views.bs_fetch_edit_data, name='bs_fetch_edit_data'),
    url(r'^bs_save_data$', views.bs_save_data, name='bs_save_data'),
    url(r'^fetch_entities$', views.fetch_entities, name='fetch_entities'),
    url(r'^add_entity$', views.add_entity, name='add_entity'),
    url(r'^get_entity$', views.get_entity, name='get_entity'),
    url(r'^edit_firm$', views.edit_firm, name='edit_firm'),
    url(r'^edit_organization', views.edit_organization, name='edit_organization'),
    url(r'^fetch_entities_all$', views.fetch_entities_all, name='fetch_entities_all'),

    url(r'^fetch_company_tele$', views.fetch_company_tele, name='fetch_company_tele'),

    url(r'^get_latest_bs_date', views.get_latest_bs_date, name='get_latest_bs_date'),
    url(r'^getlatest_bs_date_with_organization', views.getlatest_bs_date_with_organization, name='getlatest_bs_date_with_organization'),
    url(r'^dl_save_data_with_array', views.dl_save_data_with_array, name='dl_save_data_with_array'),
    url(r'^bs_get_data_mock_for_bs', views.bs_get_data_mock_for_bs, name='bs_get_data_mock_for_bs'),
    url(r'^dl_fetch_edit_data_with_array', views.dl_fetch_edit_data_with_array, name='dl_fetch_edit_data_with_array'),
    url(r'^dl_delete_data', views.dl_delete_data, name='dl_delete_data'),
    url(r'^is_enum_used_in_dl', views.is_enum_used_in_dl, name='is_enum_used_in_dl'),
    url(r'^bs_save_data_with_firm', views.bs_save_data_with_firm, name='bs_save_data_with_firm'),
    url(r'^bs_save_data_with_organization', views.bs_save_data_with_organization, name='bs_save_data_with_organization'),
    url(r'^get_summary_data_by_sector', views.get_summary_data_by_sector, name='get_summary_data_by_sector'),
    url(r'^get1_summary_data_by_sector_for_provinces', views.get1_summary_data_by_sector_for_provinces, name='get1_summary_data_by_sector_for_provinces'),

    url(r'^fetch_trans_rail_losses', views.fetch_trans_rail_losses, name='fetch_trans_rail_losses'),
    url(r'^edit_school', views.edit_school, name='edit_school'),

    # add_entity_with_district
    url(r'^add_entity_with_district$', views.add_entity_with_district, name='add_entity_with_district'),

    url(r'^dl_save_data$', views.dl_save_data, name='dl_save_data'),
    url(r'^dl_get_data$', views.dl_get_data, name='dl_get_data'),
    url(r'^dl_fetch_edit_data$', views.dl_fetch_edit_data, name='dl_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),
    url(r'^dl_fetch_summary_dis_disagtn$', views.dl_fetch_summary_dis_disagtn, name='dl_fetch_summary_dis_disagtn'),

    url(r'^update_enumirate_dl_data$', views.update_enumirate_dl_data, name='update_enumirate_dl_data'),
    url(r'^update_other_government_enumirate_dl_data$', views.update_other_government_enumirate_dl_data, name='update_other_government_enumirate_dl_data'),
    url(r'^uupdate_enumirate_dl_data_with_firms$', views.uupdate_enumirate_dl_data_with_firms, name='uupdate_enumirate_dl_data_with_firms'),
    url(r'^uupdate_enumirate_dl_data_with_organizations$', views.uupdate_enumirate_dl_data_with_organizations, name='uupdate_enumirate_dl_data_with_organizations'),

    url(r'^fetch_incident_districts$', views.fetch_incident_districts, name='fetch_incident_districts'),
    url(r'^fetch_incident_provinces$', views.fetch_incident_provinces, name='fetch_incident_provinces'),

    # get Business Types
    url(r'^fetch_business_types$', views.fetch_business_types, name='fetch_business_types'),
    url(r'^fetch_business_types_for_summary$', views.fetch_business_types_for_summary, name='fetch_business_types_for_summary'),

    # get Business Types
    url(r'^fetch_tourism_infrastructure_types$', views.fetch_tourism_infrastructure_types, name='fetch_tourism_infrastructure_types'),

    # get entities all data
    url(r'^fetch_entities_plain$', views.fetch_entities_plain, name='fetch_entities_plain'),

    url(r'^fetch_pw_gen_firms$', views.fetch_pw_gen_firms, name='fetch_pw_gen_firms'),

    url(r'^fetch_entities_plain_column$', views.fetch_entities_plain_column, name='fetch_entities_plain_column'),

    url(r'^fetch_entities_plain_column_from_district$', views.fetch_entities_plain_column_from_district, name='fetch_entities_plain_column_from_district'),

    # agri_irrigation
    url(r'^agri_irrigation/', include('agri_irrigation.urls', namespace='agri_irrigation')),

    # agri_agrarian
    url(r'^agri_agrarian/', include('agri_agrarian.urls', namespace='agri_agrarian')),

    # agri_livestock
    url(r'^agri_livestock/', include('agri_livestock.urls', namespace='agri_livestock')),
     url(r'^bs_livestock_fetch_edit_data$', views.bs_livestock_fetch_edit_data, name='bs_livestock_fetch_edit_data'),

    # agri_fisheries
    url(r'^agri_fisheries/', include('agri_fisheries.urls', namespace='agri_fisheries')),

    # agri_summary
    url(r'^agri_summary/', include('agri_summary.urls', namespace='agri_summary')),

    # water_supply
    url(r'^water_supply/', include('water_supply.urls', namespace='water_supply')),

    # power_supply
    url(r'^power_supply/', include('power_supply.urls', namespace='power_supply')),

    # housing
    url(r'^housing/', include('housing.urls', namespace='housing')),

    # telecommunication
    url(r'^telecommunication/', include('telecommunication.urls', namespace='telecommunication')),

    # tourism
    url(r'^tourism/', include('tourism.urls', namespace='tourism')),

    # industry_services
    url(r'^industry_services/', include('industry_services.urls', namespace='industry_services')),

    # other govn services
    url(r'^other_govn_services/', include('other_govn_services.urls', namespace='other_govn_services')),

    # mining
    url(r'^mining/', include('mining.urls', namespace='mining')),
    url(r'^bs_mining_fetch_edit_data$', views.bs_mining_fetch_edit_data, name='bs_mining_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_total_data$', views.dl_fetch_total_data, name='dl_fetch_total_data'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),

    # transport_rail
    url(r'^transport_rail/', include('transport_rail.urls', namespace='transport_rail')),

    # transport-water
    url(r'^transport_water/', include('transport_water.urls', namespace='transport_water')),

    # transport-land
    url(r'^transport_land/', include('transport_land.urls', namespace='transport_land')),

    # transport_air
    url(r'^transport_air/', include('transport_air.urls', namespace='transport_air')),

    # transport_summary
    url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),

    # test
    # url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),





]

charts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from settings.models import District, Province
from incidents.models import IncidentReport
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.apps import apps
from django.conf import settings
import yaml
import json


def index_chart(request):   
    return render(request, 'charts/index_chart.html')


def chart_tabel8(request):
    districts = District.objects.all()
    incidents = IncidentReport.objects.all()
    context = {
        'districts': districts,
        'incidents': incidents,
        'module': 'charts'
    }
    return render(request, 'charts/chart_tabel8.html', context)


def chart_tabel9(request):
    districts = District.objects.all()
    incidents = IncidentReport.objects.all()
    provinces = Province.objects.all()
    context = {
        'districts': districts,
        'incidents': incidents,
        'provinces': provinces,
        'module': 'charts'
    }
    return render(request, 'charts/chart_tabel9.html', context)


def chart_tabel10(request):
    districts = District.objects.all()
    incidents = IncidentReport.objects.all()
    context = {
        'districts': districts,
        'incidents': incidents,
        'module': 'charts'
    }
    return render(request, 'charts/chart_tabel10.html', context)


def education_summary(request):
    incidents = IncidentReport.objects.all()
    context = {
        'incidents': incidents,
        'module': 'charts'
    }
    return render(request, 'charts/chart_tabel10.html', context)


@csrf_exempt
def dl_fetch_chart_data(request):

    data = (yaml.safe_load(request.body))
    table_name = data['table_name']
    com_data = data['com_data']
    incident = com_data['incident']
    chart_details = data['chart_stacked_data']
    tables = settings.TABLE_PROPERTY_MAPPER[table_name]

    bs_mtable_data = {table_name: {}}

    filter_fields = {}

    if table_name == 'Table_9':
        admin_area = com_data['province']
        filter_fields = {'incident': incident, 'province': admin_area}
    elif table_name == 'Table_10':
        filter_fields = {'incident': incident}
    else:
        admin_area = com_data['district']
        filter_fields = {'incident': incident, 'district': admin_area}

    for chart_model in chart_details:
        print chart_model
        bs_mtable_data[table_name][chart_model] = {}
        for chart_type in chart_details[chart_model]:
            print chart_type
            bs_mtable_data[table_name][chart_model][chart_type] = {}
            print bs_mtable_data
            for stacked_key in chart_details[chart_model][chart_type]:
                print bs_mtable_data
                #bs_mtable_data[table_name][chart_model][chart_type][stacked_key] = {}
                print chart_details[chart_model][chart_type][stacked_key]
                table_fields = chart_details[chart_model][chart_type][stacked_key]
                model_class = apps.get_model('damage_losses', chart_model)
                chart_data = list(model_class.objects.filter(**filter_fields).values_list(*table_fields))

                #bs_mtable_data[table_name] = {chart_model: {chart_type: {stacked_key: chart_data}}}
                bs_mtable_data[table_name][chart_model][chart_type][stacked_key] = chart_data

    return HttpResponse(
        json.dumps(bs_mtable_data),
        content_type='application/javascript; charset=utf8'
    )

charts/templates/charts/chart_tabel10.html
{% extends "dashboard/base.html" %}
{% block content %}
<style>
a:hover {text-decoration:none;}
.chart {
    background: #eee;
    padding: 3px;
}

.chart div {
  width: 0;
  transition: all 1s ease-out;
  -moz-transition: all 1s ease-out;
  -webkit-transition: all 1s ease-out;
}

.chart div {
  font: 10px sans-serif;
  background-color: steelblue;
  text-align: right;
  padding: 3px;
  margin: 5px;
  color: white;
  box-shadow: 2px 2px 2px #666;
}

</style>

<!-- Main content -->
<main class="main" ng-app="dlHsNationalChartApp" ng-controller="DlHsNationalChartController">

    <!-- Breadcrumb -->
    <ol class="breadcrumb">

        <li class="breadcrumb-item"><a href="#">Admin</a>
        </li>
        <li class="breadcrumb-item active">Health Sector</li>


    </ol>


    <div class="container-fluid">

        <div class="card">
            <div class="card-header">
                <strong>Search</strong>

            </div>
            <div class="card-block">


                <div class="row" ng-form name="chart_sum_dl_national">

                    <div class="col-sm-3">

                        <div class="form-group">
                            <label for="cvv">Incident</label>
                            <select id="ccyear" name="incident" ng-model="incident" class="form-control" required>
                                <option value="">-- Select --</option>
                                {% for incident in incidents %}
                                <option value="{{ incident.id }}">{{ incident.reported_date_time }}{{
                                    incident.disaster_type }}
                                </option>
                                {% endfor %}
                            </select>
                            <span  style="color:red" ng-show="submitted && chart_sum_dl_national.incident.$error.required">
                                       Please select Incident
                            </span>
                        </div>

                    </div>


                    <div class="col-sm-2">

                        <div class="form-group">

                            <button ng-click="generateCharts(chart_sum_dl_national)" type="button" class="btn btn-sm btn-primary"
                                    style="padding:7px;margin-top:28px;"><i
                                    class="fa fa-search"></i> Search
                            </button>
                        </div>

                    </div>

                </div>
                <!--/row-->
            </div>
        </div>


<h3 style="width:100%;background:#FF5733;padding:6px;color:#fff;">Damage and Losses</h3>
<div class="row">
<div class="col-md-6">
<div class="card">
                    <div class="card-header">
                        Public Sector - Line Ministry Health System

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <div>
                                <nvd3 id="line_chart" options='options' data='dsnPubPnLmhDl' api="api1"
                                    config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                            </div>
                        </div>
                    </div>
                </div>

 <div class="card">
                    <div class="card-header">
                        Public Sector - Other Medical Facilities

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPubPnOmcDl' api="api3"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

 <div class="card">
                    <div class="card-header">
                        Ownership

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                                <nvd3 id="line_chart" options='options' data='dsnTdlOwship' api="api5"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

</div>

<div class="col-md-6">
 <div class="card">
                    <div class="card-header">
                        Public Sector - MOH

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                           <nvd3 id="line_chart" options='options' data='dsnPubPnMohDl' api="api2"
                                      config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>


 <div class="card">
                    <div class="card-header">
                        Private Sector

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPvtPnDn' api="api4"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>
</div>
</div>





       
              




  <h3 style="width:100%;background:#FF5733;padding:6px;color:#fff;">Total number of health facilities and assets affected</h3>
<div class="row">
<div class="col-md-6">
 <div class="card">
                    <div class="card-header">
                        
                        Public Sector - Line Ministry Health System

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='optionsDiscrete' data='dsnPubPnLmhTotAfc' api="api6"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

 <div class="card">
                    <div class="card-header">
                        Public Sector - Other Medical Facilities

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='optionsDiscrete' data='dsnPubPnOmcTotAfc' api="api8"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>
</div>

<div class="col-md-6">
 <div class="card">
                    <div class="card-header">
                        Public Sector - MOH

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='optionsDiscrete' data='dsnPubPnMohTotAfc' api="api7"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

 <div class="card">
                    <div class="card-header">
                        Private Sector

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='optionsDiscrete' data='dsnPvtPnTotAfc' api="api9"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>
</div>
</div>
             
<h3 style="width:100%;background:#FF5733;padding:6px;color:#fff;">Total number of patients affected</h3>
<div class="row">
<div class="col-md-6">
 <div class="card">
                    <div class="card-header">
                        
                        Public Sector - Line Ministry Health System

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPubPnLmhTotPaAfc' api="api10"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>
 <div class="card">
                    <div class="card-header">
                        Public Sector - Other Medical Facilities

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPubPnOmcTotPaAfc' api="api12"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

</div>  

<div class="col-md-6">
 <div class="card">
                    <div class="card-header">
                        Public Sector - MOH

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPubPnMohTotPaAfc' api="api11"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>
  <div class="card">
                    <div class="card-header">
                        Private Sector

                    </div>
                    <div class="card-block">
                        <div class="chart-wrapper">
                            <nvd3 id="line_chart" options='options' data='dsnPvtPnTotPaAfc' api="api13"
                                  config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>
                        </div>
                    </div>
                </div>

</div>  
</div>             
               
               
               
      <div class="animated fadeIn">
            <div class="card-columns col-2">           
               
               
               
               
               
              


            </div>
        </div>

    </div>
    <!-- /.conainer-fluid -->
    <!-- /.conainer-fluid -->
</main>
{% endblock content %}

charts/templates/charts/index_chart.html
{% extends "dashboard/base.html" %}
{% block content %}
<!-- Main content -->
<main class="main">
    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Admin</a>
        </li>
        <li class="breadcrumb-item active">
            Charts
        </li>
    </ol>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <a href="{% url 'charts:chart_tabel8' %}" style="text-decoration:none;">
                    <div class="card card-inverse card-danger text-xs-center">
                        <div class="card-block">
                            <h3> Data analysis of Damages & Losses</h3>
                            <blockquote class="card-blockquote">
                                <p>in the health sector in a district</p>
                            </blockquote>
                        </div>
                    </div>
                </a>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <a href="{% url 'charts:chart_tabel9' %}" style="text-decoration:none;">
                    <div class="card card-inverse card-danger text-xs-center">
                        <div class="card-block">
                            <h3> Data analysis of Damages & Losses</h3>
                            <blockquote class="card-blockquote">
                                <p>in the health sector in the province</p>
                            </blockquote>
                        </div>
                    </div>
                </a>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <a href="{% url 'charts:chart_tabel10' %}" style="text-decoration:none;">
                    <div class="card card-inverse card-danger text-xs-center">
                        <div class="card-block">
                            <h3> Data analysis of Damages & Losses</h3>
                            <blockquote class="card-blockquote">
                                <p> in the health sector nationwide</p>
                            </blockquote>
                        </div>
                    </div>
                </a>
            </div>
            <!--/.col-->
        </div>
    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock content %}