agri_livestock/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^base_line/', include('agri_livestock.base_line.urls', namespace='base_line')),
    url(r'^damage_losses/', include('agri_livestock.damage_losses.urls', namespace='damage_losses')),
]

dala/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from tastypie.api import Api
from .import views
# from api.resources import DistrictResource, ProvinceResource, BmfPubMfResource

# v1_api = Api(api_name='v1')
# v1_api.register(DistrictResource())
# v1_api.register(ProvinceResource())
# v1_api.register(BmfPubMfResource())

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    # url(r'^api/', include(v1_api.urls)),
    url(r'^health/', include('health.urls', namespace='health')),
    url(r'^education/', include('education.urls', namespace='education')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^new_charts/', include('new_charts.urls', namespace='new_charts')),
    url(r'^send_email', views.send_email, name='send_email'),

    # report builder
   # url(r'^report_builder/', include('report_builder.urls')),

    # common functions
    url(r'^bs_get_data$', views.bs_get_data, name='bs_get_data'),
    url(r'^bs_get_data_mock$', views.bs_get_data_mock, name='bs_get_data_mock'),
    url(r'^bs_fetch_edit_data$', views.bs_fetch_edit_data, name='bs_fetch_edit_data'),
    url(r'^bs_save_data$', views.bs_save_data, name='bs_save_data'),
    url(r'^fetch_entities$', views.fetch_entities, name='fetch_entities'),
    url(r'^add_entity$', views.add_entity, name='add_entity'),
    url(r'^get_entity$', views.get_entity, name='get_entity'),
    url(r'^edit_firm$', views.edit_firm, name='edit_firm'),
    url(r'^edit_organization', views.edit_organization, name='edit_organization'),
    url(r'^fetch_entities_all$', views.fetch_entities_all, name='fetch_entities_all'),

    url(r'^fetch_company_tele$', views.fetch_company_tele, name='fetch_company_tele'),

    url(r'^get_latest_bs_date', views.get_latest_bs_date, name='get_latest_bs_date'),
    url(r'^getlatest_bs_date_with_organization', views.getlatest_bs_date_with_organization, name='getlatest_bs_date_with_organization'),
    url(r'^dl_save_data_with_array', views.dl_save_data_with_array, name='dl_save_data_with_array'),
    url(r'^bs_get_data_mock_for_bs', views.bs_get_data_mock_for_bs, name='bs_get_data_mock_for_bs'),
    url(r'^dl_fetch_edit_data_with_array', views.dl_fetch_edit_data_with_array, name='dl_fetch_edit_data_with_array'),
    url(r'^dl_delete_data', views.dl_delete_data, name='dl_delete_data'),
    url(r'^is_enum_used_in_dl', views.is_enum_used_in_dl, name='is_enum_used_in_dl'),
    url(r'^bs_save_data_with_firm', views.bs_save_data_with_firm, name='bs_save_data_with_firm'),
    url(r'^bs_save_data_with_organization', views.bs_save_data_with_organization, name='bs_save_data_with_organization'),
    url(r'^get_summary_data_by_sector', views.get_summary_data_by_sector, name='get_summary_data_by_sector'),
    url(r'^get1_summary_data_by_sector_for_provinces', views.get1_summary_data_by_sector_for_provinces, name='get1_summary_data_by_sector_for_provinces'),

    url(r'^fetch_trans_rail_losses', views.fetch_trans_rail_losses, name='fetch_trans_rail_losses'),
    url(r'^edit_school', views.edit_school, name='edit_school'),

    # add_entity_with_district
    url(r'^add_entity_with_district$', views.add_entity_with_district, name='add_entity_with_district'),

    url(r'^dl_save_data$', views.dl_save_data, name='dl_save_data'),
    url(r'^dl_get_data$', views.dl_get_data, name='dl_get_data'),
    url(r'^dl_fetch_edit_data$', views.dl_fetch_edit_data, name='dl_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),
    url(r'^dl_fetch_summary_dis_disagtn$', views.dl_fetch_summary_dis_disagtn, name='dl_fetch_summary_dis_disagtn'),

    url(r'^update_enumirate_dl_data$', views.update_enumirate_dl_data, name='update_enumirate_dl_data'),
    url(r'^update_other_government_enumirate_dl_data$', views.update_other_government_enumirate_dl_data, name='update_other_government_enumirate_dl_data'),
    url(r'^uupdate_enumirate_dl_data_with_firms$', views.uupdate_enumirate_dl_data_with_firms, name='uupdate_enumirate_dl_data_with_firms'),
    url(r'^uupdate_enumirate_dl_data_with_organizations$', views.uupdate_enumirate_dl_data_with_organizations, name='uupdate_enumirate_dl_data_with_organizations'),

    url(r'^fetch_incident_districts$', views.fetch_incident_districts, name='fetch_incident_districts'),
    url(r'^fetch_incident_provinces$', views.fetch_incident_provinces, name='fetch_incident_provinces'),

    # get Business Types
    url(r'^fetch_business_types$', views.fetch_business_types, name='fetch_business_types'),
    url(r'^fetch_business_types_for_summary$', views.fetch_business_types_for_summary, name='fetch_business_types_for_summary'),

    # get Business Types
    url(r'^fetch_tourism_infrastructure_types$', views.fetch_tourism_infrastructure_types, name='fetch_tourism_infrastructure_types'),

    # get entities all data
    url(r'^fetch_entities_plain$', views.fetch_entities_plain, name='fetch_entities_plain'),

    url(r'^fetch_pw_gen_firms$', views.fetch_pw_gen_firms, name='fetch_pw_gen_firms'),

    url(r'^fetch_entities_plain_column$', views.fetch_entities_plain_column, name='fetch_entities_plain_column'),

    url(r'^fetch_entities_plain_column_from_district$', views.fetch_entities_plain_column_from_district, name='fetch_entities_plain_column_from_district'),

    # agri_irrigation
    url(r'^agri_irrigation/', include('agri_irrigation.urls', namespace='agri_irrigation')),

    # agri_agrarian
    url(r'^agri_agrarian/', include('agri_agrarian.urls', namespace='agri_agrarian')),

    # agri_livestock
    url(r'^agri_livestock/', include('agri_livestock.urls', namespace='agri_livestock')),
     url(r'^bs_livestock_fetch_edit_data$', views.bs_livestock_fetch_edit_data, name='bs_livestock_fetch_edit_data'),

    # agri_fisheries
    url(r'^agri_fisheries/', include('agri_fisheries.urls', namespace='agri_fisheries')),

    # agri_summary
    url(r'^agri_summary/', include('agri_summary.urls', namespace='agri_summary')),

    # water_supply
    url(r'^water_supply/', include('water_supply.urls', namespace='water_supply')),

    # power_supply
    url(r'^power_supply/', include('power_supply.urls', namespace='power_supply')),

    # housing
    url(r'^housing/', include('housing.urls', namespace='housing')),

    # telecommunication
    url(r'^telecommunication/', include('telecommunication.urls', namespace='telecommunication')),

    # tourism
    url(r'^tourism/', include('tourism.urls', namespace='tourism')),

    # industry_services
    url(r'^industry_services/', include('industry_services.urls', namespace='industry_services')),

    # other govn services
    url(r'^other_govn_services/', include('other_govn_services.urls', namespace='other_govn_services')),

    # mining
    url(r'^mining/', include('mining.urls', namespace='mining')),
    url(r'^bs_mining_fetch_edit_data$', views.bs_mining_fetch_edit_data, name='bs_mining_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_total_data$', views.dl_fetch_total_data, name='dl_fetch_total_data'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),

    # transport_rail
    url(r'^transport_rail/', include('transport_rail.urls', namespace='transport_rail')),

    # transport-water
    url(r'^transport_water/', include('transport_water.urls', namespace='transport_water')),

    # transport-land
    url(r'^transport_land/', include('transport_land.urls', namespace='transport_land')),

    # transport_air
    url(r'^transport_air/', include('transport_air.urls', namespace='transport_air')),

    # transport_summary
    url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),

    # test
    # url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),





]

dashboard/urls.py
from django.conf.urls import url
from .import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    url(r'^health_main$', views.health_main, name='health_main'),
    url(r'^mining_main$', views.mining_main, name='mining_main'),
    url(r'^othergov_main$', views.othergov_main, name='othergov_main'),
    url(r'^education_main$', views.education_main, name='education_main'),
    url(r'^transport_air_main$', views.transport_air_main, name='transport_air_main'),
    url(r'^transport_land_main$', views.transport_land_main, name='transport_land_main'),
    url(r'^transport_rail_main$', views.transport_rail_main, name='transport_rail_main'),
    url(r'^transport_water_main$', views.transport_water_main, name='transport_water_main'),
    url(r'^transport_summary_main$', views.transport_summary_main, name='transport_summary_main'),
    url(r'^agri_agrarian_main$', views.agri_agrarian_main, name='agri_agrarian_main'),
    url(r'^agri_fisheries_main$', views.agri_fisheries_main, name='agri_fisheries_main'),
    url(r'^agri_irrigation_main$', views.agri_irrigation_main, name='agri_irrigation_main'),
    url(r'^agri_livestock_main$', views.agri_livestock_main, name='agri_livestock_main'),
    url(r'^agri_summary_main$', views.agri_summary_main, name='agri_summary_main'),
    url(r'^water_supply_main$', views.water_supply_main, name='water_supply_main'),
    url(r'^power_supply_main$', views.power_supply_main, name='power_supply_main'),
    url(r'^housing_main$', views.housing_main, name='housing_main'),
    url(r'^tourism_main$', views.tourism_main, name='tourism_main'),
    url(r'^industry_services_main$', views.industry_services_main, name='industry_services_main'),
    url(r'^telecom_main$', views.telecom_main, name='telecom_main'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/admin/login/'}, name='logout'),
    # url(r'^logout/$', views.logout, name='logout'),
    # url(r'^error_main$', views.error_main, name='error_main'),
    url(r'^fetch_dashboard_data$', views.fetch_dashboard_data, name='fetch_dashboard_data'),


]

health/damage_losses/urls.py
from django.conf.urls import url
from .import views


urlpatterns = [

    url(r'^dl_health_damagelost_other_medical_facilities$', views.dl_health_damagelost_other_medical_facilities,name='dl_health_damagelost_other_medical_facilities'),
    url(r'^health_damagelost_ministry_helth$', views.health_damagelost_ministry_helth,name='health_damagelost_ministry_helth'),
    url(r'^health_damagelost_private$', views.health_damagelost_private, name='health_damagelost_private'),
    url(r'^dl_health_summary_sector_district$', views.dl_health_summary_sector_district, name='dl_health_summary_sector_district'),
    url(r'^health_summery_damageloss_province$', views.health_summery_damageloss_province, name='health_summery_damageloss_province'),
    url(r'^dl_health_summary_damage_nationwide$', views.dl_health_summary_damage_nationwide, name='dl_health_summary_damage_nationwide'),

    url(r'^fetch_entities', views.fetch_entities, name='fetch_entities'),
]

mining/damage_losses/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [

    url(r'^damages_losses_of_mining_firms', views.damages_losses_of_mining_firms, name='damages_losses_of_mining_firms'),
    url(r'^damages_losses_artisanal_mining', views.damages_losses_artisanal_mining, name='damages_losses_artisanal_mining'),
    url(r'^summary_damage_losses_district', views.summary_damage_losses_district, name='summary_damage_losses_district'),
    url(r'^summary_damage_losses_province', views.summary_damage_losses_province, name='summary_damage_losses_province'),
    url(r'^summary_damage_losses_nationwide', views.summary_damage_losses_nationwide, name='summary_damage_losses_nationwide'),
    ]

transport_summary/damage_losses/models.py
from django.db import models
from settings.models import District,Province
from incidents.models import IncidentReport


# class DlGacPubProvince(models.Model):
#     damages = models.FloatField(blank=True, null=True)
#     district = models.ForeignKey(District, db_column='district', blank=True, null=True)
#     incident = models.ForeignKey(IncidentReport, db_column='incident', blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'transport_summary\".\"dl_gac_pub_province'
#
#
# class DlGacPvtProvince(models.Model):
#     tot_damages_pvt = models.FloatField(blank=True, null=True)
#     district = models.ForeignKey(District, db_column='district', blank=True, null=True)
#     incident = models.ForeignKey(IncidentReport, db_column='incident', blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'transport_summary\".\"dl_gac_pvt_province'
#
#
# class DlYearsPubProvince(models.Model):
#     year_1 = models.FloatField(blank=True, null=True)
#     year_2 = models.FloatField(blank=True, null=True)
#     district = models.ForeignKey(District, db_column='district', blank=True, null=True)
#     incident = models.ForeignKey(IncidentReport, db_column='incident', blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'transport_summary\".\"dl_years_pub_province'
#
#
# class DlOtherLosPvtDistrict(models.Model):
#     year_1_pvt = models.FloatField(blank=True, null=True)
#     year_2_pub = models.FloatField(blank=True, null=True)
#     district = models.ForeignKey(District, db_column='district', blank=True, null=True)
#     incident = models.ForeignKey(IncidentReport, db_column='incident', blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'transport_summary\".\"dl_other_los_pvt_district'

agri_livestock/templates/damage_losses/summary_damages_losses_livestock_poultry_the_nationwide.html
{% extends "dashboard/base.html" %}
{% block content %}
{% load static %}
<!-- Main content -->
<style type="text/css">
td {
   width:8em!important;
}
</style>
<main class="main" ng-app="dlAgriLivestocknNatApp" ng-controller="DlAgriLivestocknNatController">

    <!-- Breadcrumb -->
    <ol class="breadcrumb">

         <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item"><a href="{% url 'dashboard:agri_livestock_main' %}">Agri Livestock  Sector</a>
        </li>
        <li class="breadcrumb-item active"><span class="label label-success" style="font-size:14px;">Table 6. Summary of Damages and Losses in the Livestock and Poultry Sub-sector Nationwide</span>
        </li>
          <li style="float:right;"> <a href="{% static 'dashboard/doc/4B-Agriculture-Livestock-24Jan17.pdf' %}" target="_blank" style="font-size: 18px;font-weight:bold;text-decoration: none;" class="icon-info" data-toggle="tooltip" title="Veiw Document" ></a> </li>
    </ol>
    <div class="container-fluid">


        <div id="myTabContent" class="tab-content">
            <div class="tab-pane active" id="step1">

                <table class="table table-bordered">


                    <colgroup>
                        <col width="113"/>
                        <col width="117"/>
                        <col width="122"/>
                        <col width="103"/>
                        <col width="136"/>
                        <col width="143"/>
                        <col width="63"/>
                        <col width="63"/>
                        <col width="63"/>
                    </colgroup>

                    <tr height="19" class="trhead1">
                        <td colspan="2" style="padding-left:5px;">
                            Incident
                        </td>
                        <td colspan="5" style="">

                            <select id="select" name="incident" ng-model="incident"
                                    class="form-control"
                                    style="width:100%;font-weight:400;"
                                    ng-change="changedValue(incident);fetchDlData();" required>
                                <option value="" selected="true">Select an Incident</option>
                                {% for incident in incidents %}
                                <option value={{incident.id}}>
                                    <!--{{incident.disaster_type.name}}-->
                                    <!--{{incident.reported_date_time}}-->
                                    {{incident.incident_name}}
                                </option>
                                {% endfor %}
                            </select>
                        </td>
                        <span ng-bind="user_id={{user.id}}" style="display:none;"></span>
                    </tr>
                    <tbody>
                    <table class="table table-bordered" ng-if="!checkIfNull()" >
                     <colgroup>
                        <col width="113"/>
                        <col width="117"/>
                        <col width="122"/>
                        <col width="103"/>
                        <col width="136"/>
                        <col width="143"/>
                        <col width="63"/>
                        <col width="63"/>
                        <col width="63"/>
                    </colgroup>
                        <tbody >
                        <tr class="trhead1" height="19">
                            <td rowspan="3" width="113" height="57">
                                Province
                            </td>
                            <td colspan="4" width="459" height="19">
                                Year 1
                            </td>
                            <td colspan="2" width="286" height="19">
                                Year 2
                            </td>
                            <td colspan="2" rowspan="2" width="126" height="38">
                                Total (LKR)
                            </td>
                        </tr>
                        <tr class="trhead1" height="19">
                            <td colspan="2" width="234" height="19">
                                Damages (LKR)
                            </td>
                            <td colspan="2" width="206" height="19">
                                Losses (LKR)
                            </td>
                            <td colspan="2" width="286" height="19">
                                Losses (LKR)
                            </td>
                        </tr>
                        <tr class="trsubc" height="19">
                            <td width="117" height="19">
                                Public
                            </td>
                            <td width="122" height="19">
                                Private
                            </td>
                            <td width="103" height="19">
                                Public
                            </td>
                            <td width="136" height="19">
                                Private
                            </td>
                            <td width="143" height="19">
                                Public
                            </td>
                            <td width="63" height="19">
                                Private
                            </td>
                            <td width="63" height="19">
                                Public
                            </td>
                            <td width="63" height="19">
                                Private
                            </td>
                        </tr>

                    <table class="table table-bordered" ng-if="!checkIfNull()" ng-repeat="(key, value) in dlAgriLivestockSumNat.agri_livestock.Table_6">
                     <colgroup>
                        <col width="113"/>
                        <col width="117"/>
                        <col width="122"/>
                        <col width="103"/>
                        <col width="136"/>
                        <col width="143"/>
                        <col width="63"/>
                        <col width="63"/>
                        <col width="63"/>
                    </colgroup>
                    <tbody>

                        <tr  height="20" ng-init="getTotal($index,key);">
                            <td class="tdpa" ng-bind="key" width="253" height="19" ></td>

                            <td width="147" class="right" ng-bind="value.DlpNdaPubNational[0].damages">

                            </td>
                            <td width="151" class="right" ng-bind="value.DlpNdaPvtNational[0].damages">

                            </td>
                            <td width="165" class="right" ng-bind="value.DlpLosPubNational[0].los_year_1">

                            </td>
                            <td width="170" class="right" ng-bind="value.DlpLosPvtNational[0].los_year_1">

                            </td>
                            <td width="135" class="right" ng-bind="value.DlpLosPubNational[0].los_year_2">

                            </td>
                            <td width="133" class="right" ng-bind="value.DlpLosPvtNational[0].los_year_2">

                            </td>
                            <td width="85" class="right" ng-bind="value.DlpNdaPubNational[0].damages +
                        value.DlpLosPubNational[0].los_year_1 +
                        value.DlpLosPubNational[0].los_year_2">
                            </td>
                            <td width="85" class="right" ng-bind="value.DlpNdaPvtNational[0].damages +
                        value.DlpLosPvtNational[0].los_year_1 +
                        value.DlpLosPvtNational[0].los_year_2">
                            </td>
                        </tr>
                        </tbody>
                        </table>
                    <table class="table table-bordered" ng-if="!checkIfNull()">
                     <colgroup>
                        <col width="113"/>
                        <col width="117"/>
                        <col width="122"/>
                        <col width="103"/>
                        <col width="136"/>
                        <col width="143"/>
                        <col width="63"/>
                        <col width="63"/>
                        <col width="63"/>
                    </colgroup>
                    <tbody>

                        <tr height="19">
                            <td class="tdpa" width="253" height="19">
                                GRAND TOTAL
                            </td>
                            <td width="147" class="right" ng-bind="totDmgPub()">

                            </td>
                            <td width="151" class="right" ng-bind="totDmgPvt()"  >

                            </td>
                            <td width="165" class="right" ng-bind="totLosPubY1()"  >

                            </td>
                            <td width="170" class="right"  ng-bind="totLosPvtY1()"  >

                            </td>
                            <td width="135" class="right" ng-bind="totLosPubY2()"  >

                            </td>
                            <td width="133" class="right" ng-bind="totLosPvtY2()"  >

                            </td>
                            <td width="126" class="right" ng-bind="totDmgPub() + totLosPubY1() + totLosPubY2()">

                            </td>
                            <td width="85" class="right" ng-bind="totDmgPvt() + totLosPvtY1() + totLosPvtY2()">

                            </td>

                        </tr>
                    </table>


                    <br>
                    <div class="pull-right">
                        <br>

                    </div>
            </div>


        </div>
    </div>


    <div class="col-md-12">


        <div class="modal fade" id="modal-container-218029" role="dialog" style="width:50%;margin:0 auto;"
             aria-hidden="true">
            <div class="modal-dialog" style="width:50%;">
                <div class="modal-content">
                    <div class="modal-header">

                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            ×
                        </button>
                        <h5 class="modal-title">
                            <span id="bookId"> </span>
                        </h5>
                    </div>
                    <div class="modal-body">
                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="textinput">Name</label>
                            <div class="col-md-10">
                                <input id="textinput" name="textinput" type="text" placeholder=""
                                       class="form-control input-md">

                            </div>
                        </div>
                    </div>
                    <br><br>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            Close
                        </button>
                        <button type="button" class="btn btn-primary">
                            Save changes
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.conainer-fluid -->
</main>


{% endblock content %}