dala/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# from tastypie.api import Api
from .import views
# from api.resources import DistrictResource, ProvinceResource, BmfPubMfResource

# v1_api = Api(api_name='v1')
# v1_api.register(DistrictResource())
# v1_api.register(ProvinceResource())
# v1_api.register(BmfPubMfResource())

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    # url(r'^api/', include(v1_api.urls)),
    url(r'^health/', include('health.urls', namespace='health')),
    url(r'^education/', include('education.urls', namespace='education')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^charts/', include('charts.urls', namespace='charts')),
    url(r'^new_charts/', include('new_charts.urls', namespace='new_charts')),
    url(r'^send_email', views.send_email, name='send_email'),

    # report builder
   # url(r'^report_builder/', include('report_builder.urls')),

    # common functions
    url(r'^bs_get_data$', views.bs_get_data, name='bs_get_data'),
    url(r'^bs_get_data_mock$', views.bs_get_data_mock, name='bs_get_data_mock'),
    url(r'^bs_fetch_edit_data$', views.bs_fetch_edit_data, name='bs_fetch_edit_data'),
    url(r'^bs_save_data$', views.bs_save_data, name='bs_save_data'),
    url(r'^fetch_entities$', views.fetch_entities, name='fetch_entities'),
    url(r'^add_entity$', views.add_entity, name='add_entity'),
    url(r'^get_entity$', views.get_entity, name='get_entity'),
    url(r'^edit_firm$', views.edit_firm, name='edit_firm'),
    url(r'^edit_organization', views.edit_organization, name='edit_organization'),
    url(r'^fetch_entities_all$', views.fetch_entities_all, name='fetch_entities_all'),

    url(r'^fetch_company_tele$', views.fetch_company_tele, name='fetch_company_tele'),

    url(r'^get_latest_bs_date', views.get_latest_bs_date, name='get_latest_bs_date'),
    url(r'^getlatest_bs_date_with_organization', views.getlatest_bs_date_with_organization, name='getlatest_bs_date_with_organization'),
    url(r'^dl_save_data_with_array', views.dl_save_data_with_array, name='dl_save_data_with_array'),
    url(r'^bs_get_data_mock_for_bs', views.bs_get_data_mock_for_bs, name='bs_get_data_mock_for_bs'),
    url(r'^dl_fetch_edit_data_with_array', views.dl_fetch_edit_data_with_array, name='dl_fetch_edit_data_with_array'),
    url(r'^dl_delete_data', views.dl_delete_data, name='dl_delete_data'),
    url(r'^is_enum_used_in_dl', views.is_enum_used_in_dl, name='is_enum_used_in_dl'),
    url(r'^bs_save_data_with_firm', views.bs_save_data_with_firm, name='bs_save_data_with_firm'),
    url(r'^bs_save_data_with_organization', views.bs_save_data_with_organization, name='bs_save_data_with_organization'),
    url(r'^get_summary_data_by_sector', views.get_summary_data_by_sector, name='get_summary_data_by_sector'),
    url(r'^get1_summary_data_by_sector_for_provinces', views.get1_summary_data_by_sector_for_provinces, name='get1_summary_data_by_sector_for_provinces'),

    url(r'^fetch_trans_rail_losses', views.fetch_trans_rail_losses, name='fetch_trans_rail_losses'),
    url(r'^edit_school', views.edit_school, name='edit_school'),

    # add_entity_with_district
    url(r'^add_entity_with_district$', views.add_entity_with_district, name='add_entity_with_district'),

    url(r'^dl_save_data$', views.dl_save_data, name='dl_save_data'),
    url(r'^dl_get_data$', views.dl_get_data, name='dl_get_data'),
    url(r'^dl_fetch_edit_data$', views.dl_fetch_edit_data, name='dl_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),
    url(r'^dl_fetch_summary_dis_disagtn$', views.dl_fetch_summary_dis_disagtn, name='dl_fetch_summary_dis_disagtn'),

    url(r'^update_enumirate_dl_data$', views.update_enumirate_dl_data, name='update_enumirate_dl_data'),
    url(r'^update_other_government_enumirate_dl_data$', views.update_other_government_enumirate_dl_data, name='update_other_government_enumirate_dl_data'),
    url(r'^uupdate_enumirate_dl_data_with_firms$', views.uupdate_enumirate_dl_data_with_firms, name='uupdate_enumirate_dl_data_with_firms'),
    url(r'^uupdate_enumirate_dl_data_with_organizations$', views.uupdate_enumirate_dl_data_with_organizations, name='uupdate_enumirate_dl_data_with_organizations'),

    url(r'^fetch_incident_districts$', views.fetch_incident_districts, name='fetch_incident_districts'),
    url(r'^fetch_incident_provinces$', views.fetch_incident_provinces, name='fetch_incident_provinces'),

    # get Business Types
    url(r'^fetch_business_types$', views.fetch_business_types, name='fetch_business_types'),
    url(r'^fetch_business_types_for_summary$', views.fetch_business_types_for_summary, name='fetch_business_types_for_summary'),

    # get Business Types
    url(r'^fetch_tourism_infrastructure_types$', views.fetch_tourism_infrastructure_types, name='fetch_tourism_infrastructure_types'),

    # get entities all data
    url(r'^fetch_entities_plain$', views.fetch_entities_plain, name='fetch_entities_plain'),

    url(r'^fetch_pw_gen_firms$', views.fetch_pw_gen_firms, name='fetch_pw_gen_firms'),

    url(r'^fetch_entities_plain_column$', views.fetch_entities_plain_column, name='fetch_entities_plain_column'),

    url(r'^fetch_entities_plain_column_from_district$', views.fetch_entities_plain_column_from_district, name='fetch_entities_plain_column_from_district'),

    # agri_irrigation
    url(r'^agri_irrigation/', include('agri_irrigation.urls', namespace='agri_irrigation')),

    # agri_agrarian
    url(r'^agri_agrarian/', include('agri_agrarian.urls', namespace='agri_agrarian')),

    # agri_livestock
    url(r'^agri_livestock/', include('agri_livestock.urls', namespace='agri_livestock')),
     url(r'^bs_livestock_fetch_edit_data$', views.bs_livestock_fetch_edit_data, name='bs_livestock_fetch_edit_data'),

    # agri_fisheries
    url(r'^agri_fisheries/', include('agri_fisheries.urls', namespace='agri_fisheries')),

    # agri_summary
    url(r'^agri_summary/', include('agri_summary.urls', namespace='agri_summary')),

    # water_supply
    url(r'^water_supply/', include('water_supply.urls', namespace='water_supply')),

    # power_supply
    url(r'^power_supply/', include('power_supply.urls', namespace='power_supply')),

    # housing
    url(r'^housing/', include('housing.urls', namespace='housing')),

    # telecommunication
    url(r'^telecommunication/', include('telecommunication.urls', namespace='telecommunication')),

    # tourism
    url(r'^tourism/', include('tourism.urls', namespace='tourism')),

    # industry_services
    url(r'^industry_services/', include('industry_services.urls', namespace='industry_services')),

    # other govn services
    url(r'^other_govn_services/', include('other_govn_services.urls', namespace='other_govn_services')),

    # mining
    url(r'^mining/', include('mining.urls', namespace='mining')),
    url(r'^bs_mining_fetch_edit_data$', views.bs_mining_fetch_edit_data, name='bs_mining_fetch_edit_data'),
    url(r'^dl_fetch_district_disagtn$', views.dl_fetch_district_disagtn, name='dl_fetch_district_disagtn'),
    url(r'^dl_fetch_total_data$', views.dl_fetch_total_data, name='dl_fetch_total_data'),
    url(r'^dl_fetch_summary_disagtn$', views.dl_fetch_summary_disagtn, name='dl_fetch_summary_disagtn'),

    # transport_rail
    url(r'^transport_rail/', include('transport_rail.urls', namespace='transport_rail')),

    # transport-water
    url(r'^transport_water/', include('transport_water.urls', namespace='transport_water')),

    # transport-land
    url(r'^transport_land/', include('transport_land.urls', namespace='transport_land')),

    # transport_air
    url(r'^transport_air/', include('transport_air.urls', namespace='transport_air')),

    # transport_summary
    url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),

    # test
    # url(r'^transport_summary/', include('transport_summary.urls', namespace='transport_summary')),





]

dashboard/urls.py
from django.conf.urls import url
from .import views

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
    url(r'^health_main$', views.health_main, name='health_main'),
    url(r'^mining_main$', views.mining_main, name='mining_main'),
    url(r'^othergov_main$', views.othergov_main, name='othergov_main'),
    url(r'^education_main$', views.education_main, name='education_main'),
    url(r'^transport_air_main$', views.transport_air_main, name='transport_air_main'),
    url(r'^transport_land_main$', views.transport_land_main, name='transport_land_main'),
    url(r'^transport_rail_main$', views.transport_rail_main, name='transport_rail_main'),
    url(r'^transport_water_main$', views.transport_water_main, name='transport_water_main'),
    url(r'^transport_summary_main$', views.transport_summary_main, name='transport_summary_main'),
    url(r'^agri_agrarian_main$', views.agri_agrarian_main, name='agri_agrarian_main'),
    url(r'^agri_fisheries_main$', views.agri_fisheries_main, name='agri_fisheries_main'),
    url(r'^agri_irrigation_main$', views.agri_irrigation_main, name='agri_irrigation_main'),
    url(r'^agri_livestock_main$', views.agri_livestock_main, name='agri_livestock_main'),
    url(r'^agri_summary_main$', views.agri_summary_main, name='agri_summary_main'),
    url(r'^water_supply_main$', views.water_supply_main, name='water_supply_main'),
    url(r'^power_supply_main$', views.power_supply_main, name='power_supply_main'),
    url(r'^housing_main$', views.housing_main, name='housing_main'),
    url(r'^tourism_main$', views.tourism_main, name='tourism_main'),
    url(r'^industry_services_main$', views.industry_services_main, name='industry_services_main'),
    url(r'^telecom_main$', views.telecom_main, name='telecom_main'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/admin/login/'}, name='logout'),
    # url(r'^logout/$', views.logout, name='logout'),
    # url(r'^error_main$', views.error_main, name='error_main'),
    url(r'^fetch_dashboard_data$', views.fetch_dashboard_data, name='fetch_dashboard_data'),


]

health/base_line/urls.py
from django.conf.urls import url

from .import views


urlpatterns = [

    url(r'^bs_health_status$', views.bs_health_status, name='bs_health_status'),
    url(r'^bs_health_medical_facilities$', views.bs_health_medical_facilities, name='bs_health_medical_facilities'),
    url(r'^bs_health_info_unit_cost_ministry_health$', views.bs_health_info_unit_cost_ministry_health, name='bs_health_info_unit_cost_ministry_health'),
    url(r'^bs_health_other_medical_facilities_unit_cost$', views.bs_health_other_medical_facilities_unit_cost, name='bs_health_other_medical_facilities_unit_cost'),

]

mining/base_line/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^mn_bs_info_industrial$', views.mn_bs_info_industrial, name='mn_bs_info_industrial'),
    url(r'^mn_bs_info_artisanal$', views.mn_bs_info_artisanal, name='mn_bs_info_artisanal'),

    url(r'^get_ownership_firm$', views.get_ownership_firm, name='get_ownership_firm'),
    # url(r'^fetch_firms$', views.fetch_firms, name='fetch_firms'),
    url(r'^add_firm$', views.add_firm, name='add_firm'),
    url(r'^edit_firm$', views.edit_firm, name='edit_firm'),

]

power_supply/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^base_line/', include('power_supply.base_line.urls', namespace='base_line')),
    url(r'^damage_losses/', include('power_supply.damage_losses.urls', namespace='damage_losses')),
]

mining/base_line/models.py
from __future__ import unicode_literals
from django.db import models
from settings.models import District


class Firm(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    ownership = models.CharField(max_length=50, blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_bs_firm_district', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"firm'


class BdSessionKeys(models.Model):
    data_type = models.CharField(max_length=120, blank=True, null=True)
    key = models.BigIntegerField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    user = models.IntegerField(blank=True, null=True)
    bs_date = models.CharField(max_length=255, blank=True, null=True)
    table_name = models.CharField(max_length=255, blank=True, null=True)
    full_bs_date = models.DateField(blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_bs_district', blank=True, null=True)
    firm = models.ForeignKey(Firm, db_column='firm_id', related_name='firm_bs', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"bd_session_keys'


class BmaAmMin(models.Model):
    minerals = models.CharField(max_length=255, blank=True, null=True)
    avg_per_year = models.FloatField(blank=True, null=True)
    bs_date = models.CharField(max_length=255, blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_BmaAmMin_district', blank=True, null=True)
    created_user = models.IntegerField(blank=True, null=True)
    lmu = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    lmd = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"bma_am_min'


class BmaAmMinNum(models.Model):
    male = models.IntegerField(blank=True, null=True)
    female = models.IntegerField(blank=True, null=True)
    bs_date = models.CharField(max_length=255, blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_BmaAmMinNum_district',  blank=True, null=True)
    created_user = models.IntegerField(blank=True, null=True)
    lmu = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    lmd = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"bma_am_min_num'


class BmaImFn(models.Model):
    name_min_outputs = models.CharField(max_length=255, blank=True, null=True)
    avg_per_year = models.FloatField(blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_BmaImFn_district', blank=True, null=True)
    created_user = models.IntegerField(blank=True, null=True)
    lmu = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    lmd = models.DateTimeField(blank=True, null=True)
    bs_date = models.CharField(max_length=12, blank=True, null=True)
    firm = models.ForeignKey(Firm, blank=True, db_column='firm_id', null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"bma_im_fn'


class BmaImFirmNum(models.Model):
    male = models.IntegerField(blank=True, null=True)
    female = models.IntegerField(blank=True, null=True)
    bs_date = models.CharField(max_length=255, blank=True, null=True)
    district = models.ForeignKey(District, db_column='district', related_name='mi_BmaImFirmNum_district', blank=True, null=True)
    created_user = models.IntegerField(blank=True, null=True)
    lmu = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    lmd = models.DateTimeField(blank=True, null=True)
    firm = models.ForeignKey(Firm, blank=True, db_column='firm_id', null=True)

    class Meta:
        managed = False
        db_table = 'mining\".\"bma_im_firm_num'

agri_agrarian/base_line/views.py
from django.shortcuts import render
from dala.views import fetch_districts
from users.decorators import permission_required
from django.views.decorators.csrf import csrf_protect, csrf_exempt


# Table 1
@permission_required("district", "agri_agrarian")
def bs_nopopl_agrb_actv(request):
    user = request.user
    fetch_data = fetch_districts(user)
    filtered_districts = fetch_data['districts']
    filtered_user = fetch_data['user']

    context = {
        'user': filtered_user,
        'districts': filtered_districts,
        'module': 'agri_agrarian'
    }
    return render(request, 'base_line/baseline_information_areas_cultivated_number_of_people_agrarian_activities.html', context)


# Table 2
@permission_required("district", "agri_agrarian")
def bs_info_acfo_assets(request):
    user = request.user
    fetch_data = fetch_districts(user)
    filtered_districts = fetch_data['districts']
    filtered_user = fetch_data['user']

    context = {
        'user': filtered_user,
        'districts': filtered_districts,
        'module': 'agri_agrarian'
    }
    return render(request, 'base_line/baseline_information_agricultural_crops_forest_products_related_other_assets.html', context)


# Table 3
@permission_required("district", "agri_agrarian")
def bs_info_sero_assets(request):
    user = request.user
    fetch_data = fetch_districts(user)
    filtered_districts = fetch_data['districts']
    filtered_user = fetch_data['user']

    context = {
        'user': filtered_user,
        'districts': filtered_districts,
        'module': 'agri_agrarian'
    }
    return render(request, 'base_line/baseline_information_structures_office_equipment_related_other_assets.html', context)

power_supply/templates/base_line/base_line_power_generation_firms_district.html
{% extends "dashboard/base.html" %}
{% block content %}
{% load static %}
<!-- Main content -->
<main class="main" ng-app="bsPowGenFrimDisApp" ng-controller="BsPowGenFrimDisController">
    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:index' %}">
                Dashboard
            </a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:power_supply_main' %}">
                Power Supply Sector
            </a>
        </li>
        <li class="breadcrumb-item active">
            <span class="label label-success" style="font-size:14px;">
                Table 1. Power Generation Firms in a District
            </span>
        </li>
        <li style="float:right;">
            <a href="{% static 'dashboard/doc/2-Power Supply-24Jan17.pdf' %}" target="_blank"
                style="font-size: 18px;font-weight:bold;text-decoration: none;" class="icon-info"
                data-toggle="tooltip" title="Veiw Document">
            </a>
        </li>
    </ol>
    <div class="container-fluid">
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane active" id="step1" ng-form name="form_power_firm_dis">
                <table class="table table-bordered">
                    <colgroup>
                        <col width="244"/>
                        <col width="112"/>
                        <col width="108" span="2"/>
                        <col width="103"/>
                        <col width="107"/>
                        <col width="111" span="2"/>
                    </colgroup>
                    <tbody>
                        <tr style="background:#fff;border:1px solid #fff;text-align:center;">
                            <td style="background:#fff;border:1px solid #fff;text-align:center;" border="0">
                            </td>
                            <td colspan="1" style="background:#fff;border:1px solid #fff;text-align:center;">
                                <span class="arrow_box" ng-show="submitted && form_power_firm_dis.district.$error.required">
                                    Please select District
                                </span>
                            </td>
                            <td colspan="2" style="background:#fff;border:1px solid #fff;text-align:center;">
                            </td>
                            <td colspan="1" style="background:#fff;border:1px solid #fff;text-align:center;">
                                <span class="arrow_box" ng-show="submitted && form_power_firm_dis.baselineDate.$error.required">
                                    Please select Date
                                </span>
                            </td>
                        </tr>
                        <tr class="trhead1" height="19">
                            <td style="padding-left:5px;"> Name of District</td>
                            <td colspan="" style="">
                                <select ng-model="district" id="selectbasic" ng-change="changeDis()" name="district"
                                        class="form-control"
                                        style="font-weight:400;" required>
                                    <option value="">Select District</option>
                                    {% for district in districts %}
                                    <option value="{{ district.id }}">{{ district.name }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td colspan="4" style="padding-right:5px;text-align:right;">
                                Year/Month
                            </td>
                            <td colspan="2" style="font-weight:normal;">
                                <input name="baselineDate" type="text" placeholder="mm/yy" ng-change="changeDis()"
                                       id="datepicker" ng-model="bs_date"
                                       class="form-control input-md" required>
                            </td>
                             <td style="width:100px;"> <span ng-if="!check_search">
                                        <button ng-if="!is_search" class="btn btn-info" disabled><span class="fa fa-search"></span></button>
                        </span> <span ng-if="check_search">
                                        <button ng-click="searchBsData(form_power_firm_dis)" ng-if="!is_search" class="btn btn-info"><span class="fa fa-search"></span></button>
                        </span>
                        <button ng-click="clear()" ng-if="is_search" class="btn  btn-warning"> <span class="fa fa-times" aria-hidden="true"></span></button>
                    </td>
                            <span ng-bind="user_id={{user.id}}" style="display:none;"></span>
                        </tr>
                        <tr class="trheadc1" height="19">
                            <td rowspan="2" height="62" width="244">
                                Power generation plants by ownership
                            </td>
                            <td rowspan="2" width="107">
                                Name
                            </td>
                            <td rowspan="2" width="107">
                                Other Description
                            </td>
                            <td colspan="3" width="431">
                                Number of Power Plants
                            </td>
                            <td width="107">
                            </td>
                            <td rowspan="2" width="111">
                                Total Capacity (kW)
                            </td>
                            <td rowspan="2" width="111">
                                Average Income per Year (LKR/Year)
                            </td>
                        </tr>
                        <tr class="trsubc" height="43">

                            <td height="43" width="112">
                                Hydro
                            </td>
                            <td width="108">
                                Coal
                            </td>
                            <td width="108">
                                Diesel
                            </td>
                            <td width="103">
                                Others
                            </td>
                        </tr>
                        <tr class="tdpa" height="19">
                            <td class="tdpa" height="19" width="244">
                                Power generation plants &nbsp;&nbsp;
                                <button ng-click="insertFirm('BsPwGenFirm')" class="btn btn-sm btn-info btn-circle"
                                        id="insert"><span
                                        class="fa fa-plus"></span>
                                </button>
                            </td>
                            <td colspan="8" width="112">
                            </td>
                        </tr>
                        <tr height="19" ng-repeat="bsPwGenFirm in bsPowGenFrimDis.power_supply.Table_1.BsPwGenFirm">
                        <td width="98">
                            {% verbatim %}
                            <button id="delete" ng-click="removeItem('BsPwGenFirm', $index)"
                                    class="btn btn-sm btn-danger btn-circle"><i class="fa fa-minus"></i></button>
                            <select id="selectbasic" ng-model="bsPwGenFirm.ownership" class="form-control"
                                    popover="This field is required" required
                                    popover-toggle="form_pop_lat_census['bsPwGenFirm_' + $index].$dirty && !form_pop_lat_census['bsPwGenFirm_' + $index].$valid"
                                    name="bsPwGenFirm_{{$index}}" type="text" placeholder=""
                                    style="width:80%;float:right;font-weight:400;">
                                <option value="" selected>Select ownership</option>
                                <option value="CEB">CEB</option>
                                <option value="IPP">IPP</option>
                                <option value="SPPA">SPPA</option>
                            </select>
                            {% endverbatim %}
                        </td>
                        <td width="112">
                            <input id="textinput" name="textinput" type="text" ng-model="bsPwGenFirm.assets"
                                   placeholder="" class="form-control input-md">
                        </td>
                        <td width="108">
                            <input id="textinput" name="textinput" type="text" ng-model="bsPwGenFirm.description"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="108">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.num_hydro"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="103">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.num_coal"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="107">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.num_diesel"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="111">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.num_other"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="111">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.tot_capacity"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                        <td width="111">
                            <input id="textinput" name="textinput" type="number" ng-model="bsPwGenFirm.avg_income"
                                   placeholder=""
                                   class="form-control input-md">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="pull-right">
                    <br>
                    <button id="clearbtn" type="button" ng-click="clear()" class="btn btn-info">
                        Clear
                    </button>
                    <span ng-if="is_edit_disable">
                        <button id="editbtn" type="button" ng-click="editBsData(form_power_firm_dis)" ng-if="!is_edit" class="btn btn-success">
                            Edit
                        </button>
                    </span>
                    <span ng-if="!is_edit_disable">
                        <button id="editbtn" type="button" ng-else="!is_edit" class="btn btn-success" disabled>
                            Edit
                        </button>
                    </span>
                    <button id="editbtn" type="button" ng-click="cancelEdit()" ng-if="is_edit" class="btn btn-warning">
                        Cancel Edit
                    </button>
                    <button id="subbtn" type="button" ng-click="saveBsData(form_power_firm_dis)" class="btn btn-success">
                        Submit
                    </button>
                </div>
                <br>
                <br>
            </div>
        </div>
    </div>
    <!-- /.conainer-fluid -->
</main>
{% endblock content %}